config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users

  resources :products do
    resources :comments
  end

  post 'payments/create'
  
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  
  mount ActionCable.server => '/cable'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  scope :rating_desc, -> { order(rating: :desc) }

  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }

  after_create_commit { CommentUpdateJob.perform_later(self, self.user) }  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_admin, only: :destroy

  def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to product_path(@product, :anchor => "reviews"), notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
#       ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        format.html { redirect_to @product, notice: 'Review was created successfully.' }
      else
        format.html { redirect_to @product, alert: 'Review could not be saved: Please provide your comment and a star rating.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product, notice: 'Review was destroyed successfully.' 
  end

  private

  def comment_params
    params.require(:comment).permit(:user_id, :body, :rating)
  end

  def authorize_admin
    if current_user.blank? || !current_user.admin?
      redirect_to root_path, alert: 'Admins only!'
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<h6>
    <%= comment.user.first_name %> 
    <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>
    <% if current_user && current_user.admin? %>
        <%= link_to ('<ion-icon name="close"></ion-icon>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: {confirm: "Are you sure?"}%>
    <% end %>
    
</h6>
<div class="rated" data-score="<%= comment.rating %>"></div>
<p><%= comment.body %></br>
</p>

app/views/comments/create.js.erb
$("#new_comment").html("Thank you for your review!");   
$("#average-rating")
  .raty("readOnly", false)
  .raty("score", <%= @product.average_rating %>)
  .attr('data-score', <%= @product.average_rating %>)
  .raty("readOnly", true);