config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users

  resources :products do
    resources :comments
  end

  post 'payments/create'
  
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  
  mount ActionCable.server => '/cable'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :orders
  has_many :comments, :dependent => :destroy
  validates :image_url, url: true
  validates :name, presence: true
  
  def price_show
    "€ %.2f" % (self[:price]/100.0)
  end

  def price
    self[:price]
  end

  def highest_rating_comment
    comments.rating_desc.first
  end

  def lowest_rating_comment
    comments.rating_desc.last
  end

  def average_rating
    comments.average(:rating).to_f
  end

  if ENV['RAILS_ENV'] == "development" then
    def self.search(search_term)
      Product.where("name LIKE ?", "%#{search_term}%")
    end
  elsif ENV['RAILS_ENV'] == "production" then
    def self.search(search_term)
      Product.where('name ilike ?', "%#{search_term}%")
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authorize_admin, except: %i(show index)
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :purge_redis_product_index, only: [:create, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    logger.debug "getting the search word and displaying corresponding items"
    if params[:q]
      search_term = params[:q]
      logger.debug "Collected search term: #{search_term}"
      @products = Product.search(search_term)
      logger.debug "Displaying corresponding items: #{@products}"
    else
      @products = $redis.get("product_index")
      if @products == nil
        @products = Product.all
        $redis.set("product_index", Marshal.dump(@products))
      else
        @products = Marshal.load @products
      end
    end
  end


  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @comments = @product.comments.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    def purge_redis_product_index
      $redis.del("product_index")
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :toxicity, :price)
    end

    def authorize_admin
      if current_user.blank?
        redirect_to user_session_path, alert: 'You have to be logged in to do that.'
      elsif !current_user.admin?
        redirect_to root_path, alert: 'Sorry, only admins can do that.'
      end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
    def cache_key_for_products
      count          = @products
      max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
      "products/all-#{count}-#{max_updated_at}"
    end

end

app/views/products/_comments.html.erb
<div class="form">
    <% @comments.each do |comment| %>
        <%= render :partial => "comments/comment", locals: {comment: comment} %>
    <% end %>
    <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true, class: "product-form col-md-8") do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-row">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="form-group">
      <%= form.label :image_url %>
      <%= form.text_field :image_url, placeholder: "Please insert a valid URL." %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group">
      <%= form.label :toxicity %>
      <%= form.text_field :toxicity %>
    </div>

    <div class="form-group">
      <%= form.label :price %>
      <%= form.text_field :price %>
    </div>
  </div>
  
  <div class="form-row">
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, placeholder: "What's special about this mushroom?" %>
      </div>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <%= form_for([@product, @product.comments.build], class:"comment-form",  remote: true) do |f| %>
    <h5>Write a new comment</h5>
    <div class="form-row">
      <div class="form-group">
        <%= f.label :rating, "How many stars would you give this mushroom?" %>
        <div class="rating"></div>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group">
        <%= f.label :body, "Your Comment" %>
        <%= f.text_area :body %>
      </div>
    </div>

    <div class="actions">  
      <%= f.submit "Submit" %>
    </div>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
  <div class="product-card">
    <%= image_tag(product.image_url, class: "img-fluid product-prev-img") %>
    <div class="card-content">
      <h3 class="product-name"><%= link_to product.name, product_path(product), class:"product-link" %></h3>
      <% logger.debug "Product: #{product.name}"%>
      <p><%= product.description %></p>
      <p><%= product.toxicity %></p>
      <p class="price"><strong><%= product.price_show %></strong></p>
      <% if current_user && current_user.admin? %>
        <div class="additional-options">
          <span><%= link_to 'Show', product_path(product) %></span>
          <span><%= link_to 'Edit', edit_product_path(product) %></span>
          <span><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/_products.html.erb
<div class="product-card">
    <%= image_tag(product.image_url, class: "img-fluid product-prev-img") %>
    <div class="card-content">
      <a href="#"><h3><%= product.name %></h3></a>
      <p><%= product.description %></p>
      <p><%= product.toxicity %></p>
      <p class="price"><strong><%= product.price %></strong></p>
      <div class="additional-options">
        <span><%= link_to 'Show', product %></span>
        <span><%= link_to 'Edit', edit_product_path(product) %></span>
        <span><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></span>
      </div>
    </div>
</div>

app/views/products/edit.html.erb
<div class="content-box skew first-box">
  <h1>Editing Product</h1>
  <div class = "unskew">
    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-primary"><%= alert %></p>
    <% end %>
    <div>
      <%= render 'form', product: @product %>
      <hr>
      <%= link_to 'Go back', products_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class="content-box skew first-box">
  <h1>Products</h1>
  <div class = "unskew">
      <% if notice %>
        <p id="notice" class="alert alert-primary"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p id="alert" class="alert alert-primary"><%= alert %></p>
      <% end %>
      <% cache(cache_key_for_products) do %>
      <div class="product-grid">
        <% @products.each do |product| %>
          <%= render partial: 'product', locals: {product: product, current_user: current_user} %>
        <% end %>
      </div>
      <% end %>
    <hr>
    <% if current_user && current_user.admin? %>
      <%= link_to 'New Product', new_product_path %>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="content-box skew first-box">
  <h1>Create a new product.</h1>

  <div class="unskew">
    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-primary"><%= alert %></p>
    <% end %>
    <%= render 'form', product: @product %>
    <hr>
    <%= link_to 'Go back', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<div class="skew">
  <div class="unskew-image-box">
    <img src= "<%= asset_path(@product.image_url) %>" data-zoom-image="<%=asset_path(@product.image_url) %>" class="img-zoom"/>
  </div>
</div>
<div class="content-box skew">
  <h1>
    <%= @product.name %>
  </h1>
  
  <div class = "unskew">
    <% if notice %>
      <p id="notice" class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" class="alert alert-primary"><%= alert %></p>
    <% end %>

    <div class="product-content col-md-8">
      <div id="product-description" data-product-id="<%= @product.id %>">
        <p><%= @product.description %></p>
        <div class="info-section">
        <div class="alert alert-info" style="display:none" role="alert">A new comment was posted!</div>
          <% if @comments %>
            <h5>Average rating</h5>
            <div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div> 
          <% end %>
        </div>
        <div class="info-section">
          <h5>Our price</h5>
          <strong><%= @product.price_show %></strong>
        </div>

      </div>


      <div id="product-additional">
        <h5>How toxic is this mushroom?</h5>
        <%= @product.toxicity %>
        <hr>
        <%= form_with(url: '/payments/create') do |form| %>
        <%= render partial: "devise/shared/stripe_checkout_button" %>
        <% end %>
        <hr>
      </div>
        
      
      <div id="product-reviews">
        <%= render 'new_comment' %>
        <hr>
        <% if @comment && @comment.size >=2 %>
          <h5>Comment with the highest rating</h5>
          <h6><%=  @product.highest_rating_comment.user.first_name %> 
            <small><em><%= "#{time_ago_in_words( @product.highest_rating_comment.created_at)} ago" %></em></small>
          </h6>
          <div class="rated" data-score="<%=  @product.highest_rating_comment.rating %>"></div>
          <p>
            <%=  @product.highest_rating_comment.body %>
          </p>
          <hr>
          <h5>Comment with the lowest rating</h5>
          <h6>
            <%= @product.lowest_rating_comment.user.first_name %> 
            <small><em><%= "#{time_ago_in_words( @product.lowest_rating_comment.created_at)} ago" %></em></small>
          </h6>
          <div class="rated" data-score="<%=  @product.lowest_rating_comment.rating %>"></div>
          <p>
            <%=  @product.lowest_rating_comment.body %>
          </p>
          <hr>
        <% end %>
        <h5>All comments</h5>
        <div class="info-section" id="all-comments">
          <%= render 'comments' %>
        </div>
      </div>
      <div>
        <hr>
        <%= link_to 'Edit', edit_product_path(@product) %>
        <%= link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%= link_to 'Back', products_path %>
      </div>
    </div>

  </div>
</div>