config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: "registrations"}
  resources :users

  resources :products do
    resources :comments
  end

  post 'payments/create'
  
  resources :orders, only: [:index, :show, :create, :destroy]
  get 'simple_pages/about'
  get 'simple_pages/contact'
  get 'simple_pages/index'
  post 'simple_pages/thank_you'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'
  
  mount ActionCable.server => '/cable'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_scope :user do
    delete 'logout', to: 'devise/sessions#destroy'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Wild Mushroom Hunt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,900" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://unpkg.com/ionicons@4.2.5/dist/ionicons.js" defer></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-dark navigation skew">
      <div class="unskew">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navigation-items" id="navbarNav">
        <%= link_to root_path, class:"navbar-brand" do %>
          <%=image_tag("mushroom_logo.svg", :alt => "mushrooming") %>
        <% end %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "Home", root_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Products", products_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to "About", simple_pages_about_path, :class => 'nav-link' %></li>
            <li class="nav-item"><%= link_to "Contact", simple_pages_contact_path, :class => 'nav-link' %></li>
          </ul>
          <%= form_with(url: products_path, method: 'get', local: true, class: "search-form") do |form| %>
            <label>
              <span class="visually-hidden">Search for</span>
              <%= form.text_field :q, value: params[:q] %>
            </label>
            <label>
              <ion-icon name="search" class="submit-icon"></ion-icon>
              <%= form.submit '' %>
            </label>
          <% end %>
              <ul class="navbar-nav dropdown">
                <% if user_signed_in? %>
                <a class="nav-item dropdown-toggle nav-link"id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Profile</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to('Logout', destroy_user_session_path, method: :delete, class:"nav-link")%>
                  <%= link_to('Edit profile', edit_user_registration_path, class:"nav-link")%>
                </div>
              <% else %>
                  <li class="nav-item">
                    <%= link_to('Login', new_user_session_path, class:"nav-link")%>
                  </li>
              <% end %>
              </ul>  
        </div>
      </div>
    </nav>
    <main>
      <%= yield %>
    </main>
    <footer class="skew">
      <h1>Contact</h1>
      <div class="unskew">
        <div>
          <p>If there's a mushroom, toadstool or fungi related item you don't see here, feel free to email us.  If we don't stock it, we can most likely get it for you during the next hunting expedition.  Any other questions, comments or suggestions, we're just an email away!</p>
          <p>+49 082 123 456 789</p>
          <p>mushroombooty@toadstool.net</p>
        </div>
        <div>
          <h5>You'll find us here</h5>
          <p>The Wild Mushroom Hunt<br>
          Spore Street 59<br>
          85182 Summercep
          </p>
        </div>
        <div>&copy; 2018 The Wild Mushroom Hunt</div>
      </div>
    </footer>
    <div class="footer-hidden">
    </div>
  </body>
</html>